//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialFly
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Brand()
        {
            this.SocialUsers = new HashSet<SocialUser>();
        }
    
        public int BrandId { get; set; }
        public string CompanyName { get; set; }
        public string Product { get; set; }
        public string ProductDescription { get; set; }
        public int PostId { get; set; }
        public int CompId { get; set; }
    
        public virtual Compensation Compensation { get; set; }
        public virtual Post Post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocialUser> SocialUsers { get; set; }
    }
}
